FROM apache/airflow:2.8.1-python3.10

# Instala pymysql dentro de la imagen
RUN pip install pymysql
RUN pip install hdfs
RUN pip install requests beautifulsoup4
RUN pip install python-chess

CMD ["/bin/bash"]
